config/routes.rb
Rails.application.routes.draw do

  resources :sub_hoods
  resources :hoods, only: [:show, :index]
  resources :users

  get 'games', to: 'games#index'
  get 'games/round', to: 'games#round'
  post 'games/round', to: 'games#answer'
  get '/games/game_end', to: 'games#game_end'

  post '/', to: 'sessions#create'
  get '/logout', to: 'sessions#logout'
  get '/resources', to: 'hoods#resources'
  root 'users#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :rounds
  has_many :users, through: :rounds
end

app/models/hood.rb
class Hood < ApplicationRecord
  has_many :users
  has_many :sub_hoods

  def name_with_id
    "#{self.id - Hood.all.min_by(&:id).id + 1} - #{self.name}"
  end
end

app/models/round.rb
class Round < ApplicationRecord
  belongs_to :game
  belongs_to :user
  belongs_to :waste
end

app/models/sub_hood.rb
class SubHood < ApplicationRecord
  belongs_to :hood
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  belongs_to :hood
  has_many :rounds
  has_many :games, through: :rounds

  validates :name, presence: true
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true
  validates :password_confirmation, presence: true
  validates :hood, presence: true

  def points
    @points ||= 0
    Round.all.each do |round|
      if round.user_id == self.id
        @points += round.score
      end
    end
    @points
    # @points = Round.all.inject(0) {|points, round| points += round.score if round.user_id == self.id}
  end

  def level
    case self.points
      when 0..49
        "Level 1 - Seed"
      when 50..199
        "Level 2 - Sapling"
      when 200..399
        "Level 3 - Shrub"
      when 400..599
        "Level 4 - Tree"
      when 600..999
        "Level 5 - Forest"
      else
        "Level 6 - Captain Planet"
    end
  end

end

app/models/waste.rb
class Waste < ApplicationRecord
  has_many :rounds
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in

    def logged_in
      !session[:user_id].nil?
    end

end

app/controllers/games_controller.rb
  class GamesController < ApplicationController
  before_action :set_round, only: [:round, :answer]

  def index
    if logged_in
      # sets the total rounds in the game
      @num_rounds = 5
      game = Game.create

      session[:rounds] = []
      session[:round] = 1
      session[:points] = 0
      session[:point_value] = 10
      session[:hood] = User.find(session[:user_id]).hood.name
      session[:message] = nil
      session[:message_cat] = nil

      waste_ids = Waste.ids.sample(@num_rounds)
      waste_ids.each do |waste_id|
        round = Round.create(user_id: session[:user_id], game_id: game.id, waste_id: waste_id, score: 0)
        session[:rounds] << round.id
      end

    end

  end

  def round
    # set session[:waste] to the waste obj at the current round's index
    @waste = session[:waste] = Waste.find(@round.waste_id)
  end

  def answer
    # byebug
    if params[:commit] == session[:waste]['category']
      session[:points] += session[:point_value]
      @round.update(score: session[:point_value])
      session[:message] = self.right_answer
    else
      session[:message_cat] = "wrong"
      session[:message] = "Actually, #{session[:waste]['name']} go in the #{session[:waste]['category']}."
    end

    session[:round] += 1
    if session[:round] > session[:rounds].size
      # if round is greater than total rounds, end game
      redirect_to '/games/game_end'
    else
      redirect_to '/games/round'
    end
  end

  def right_answer
    session[:message_cat] = "right"
    [
      "Nice job!",
      "Excellent work!",
      "Way to go!",
      "That's right!"
      # "You're crushing it!",
      # "Observe the lamentation of your enemies!",
      # "War is hell, except when you're winning!",
      # "Your hood will reign victorious!",
      # "Waste fears you!",
      # "Another notch on your belt!",
      # "The park just got a little nicer!",
      # "The rivers run a little cleaner today.",
      # "Post-apocalypse, shmost-apocalypse!",
      # "You can start to see the ground again!",
      # "Incredible!",
      # "Victory!",
      # "A greener planet awaits!",
      # "You must be out of bubblegum!",
      # "Seattle's bards will sing songs about you!"
    ].sample
  end

  def game_end
    # total up score, add to user's score, add to hood's score
    @points = session[:points]
    session[:points] = 0
    @hood = Hood.find_by(name: session[:hood])
    @hood.update(hood_score: @hood.hood_score + @points)
  end

  private

    def set_round
      @round_no = session[:round]
      @round = Round.find(session[:rounds][@round_no - 1])
    end

end

app/controllers/hoods_controller.rb
class HoodsController < ApplicationController


  def index
    @hoods = Hood.all
  end

  def show
    @hood = Hood.find(params[:id])
    @users = User.all
  end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create #login
    @user = User.find_by(username: params[:username])
    # byebug
    if @user
      if @user.authenticate(params[:password])
        session[:user_id] = @user.id
        flash[:message] = "Welcome back #{@user.username}!"
        redirect_to '/'
      else
        flash[:message] = "Incorrect Login information"
        redirect_to '/'
      end
    else
      flash[:message] = "Incorrect Login information"
      redirect_to '/'
    end
  end

  def logout
    session.clear
    redirect_to '/'
  end


end

app/controllers/sub_hoods_controller.rb
class SubHoodsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy]

  def index
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      @errors = @user.errors.full_messages
      render :new
    end
  end

  def edit
    render :new
  end

  def update
    if @user.update(user_params)
      redirect_to "/users/#{@user.id}"
    else
      @errors = @user.errors.full_messages
      render :new
    end
  end

  def destroy
    @user.destroy
    session.clear
    flash[:message] = "Profile Deleted!"
    redirect_to '/'
  end

  private
    def set_user
      if logged_in
        @user = User.find(session[:user_id])
      else
        redirect_to '/'
      end
    end

    def user_params
      params.require(:user).permit!
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hoods_helper.rb
module HoodsHelper
end

app/helpers/sub_hoods_helper.rb
module SubHoodsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/game_end.erb
<div class="game-intro">

<% if session[:message_cat] == "right" %>
  <h3 class="message"><%= session[:message] %></h3>
<% else %>
  <h3 class="message error"><%= session[:message] %></h3>
<% end %>

<h3>Thanks for playing!</h3>
<br>
<h4>You Greened Up your neighborhood by <%= @points %> points!</h4>
<br>
<h4> <%= @hood.name %> now has a total of <%= @hood.hood_score %> points.</h4>
<br>
<center><a href='/games' class="btn btn-success">PLAY AGAIN</a> &nbsp; <a href='/hoods' class="btn btn-primary">See Your Hood's Rank</a></center>

</div>

app/views/games/index.html.erb
  <h1>Bin It to Win It!</h1>

  <% if logged_in %>
  <div class="game-intro">

  <h3>Confused about where your garbage should go?</h3>
  <h4>Play 'Bin It to Win It' to improve your trash tossing skills and help fight misplaced waste to Green Up your neighborhood!</h4>
<hr>
<h4>Instructions:</h4>

    <p>Each round you will be shown a common waste item.</p>
    <p>Select the correct bin and get 10 points!</p>
    <p>You'll have <%= @num_rounds %> rounds to test your knowledge.</p>
    <p>The more points you get, the greener your 'hood gets!</p>
    <p>Press start to play!</p>


  <center><a href='/games/round' class="btn btn-success">START</a></center>
</div>
<% else %>
  <h3 class="message">You must <a href='/' style="color: white">log in</a> to play!</h3>

<% end %>

app/views/games/round.html.erb
<div class="game-round">

  <h2>Round <%= session[:round] %></h2>
  <% if session[:message_cat] == "right" %>
    <h3 class="message"><%= session[:message] %></h3>
  <% else %>
    <h3 class="message error"><%= session[:message] %></h3>
  <% end %>

  <h3>Points: <%= session[:points] %></h3>
  <br>

  <img class="wastepic" src="<%= @waste.img_url %>" alt="<%= @waste.name %>" />
  <h4>( <%= @waste['name'] %> )</h4>

  <h3>Which bin does this go in?</h3>

  <br>
  <%= form_tag ({controller: 'games', action: 'round', method: 'post'}) do %>
    <input type="submit" name="commit" value="trash" data-disable-with="trash" style="background: url('/images/buttons/trash-button.png') no-repeat center center; width: 60px; height: 60px; margin: 0px 20px; border: none; color: transparent; border-radius: 5px">

    <input type="submit" name="commit" value="recycling" data-disable-with="recycling" style="background: url('/images/buttons/recycle-button.png') no-repeat center center; width: 60px; height: 60px; margin: 0px 20px; border: none; color: transparent; border-radius: 5px">

    <input type="submit" name="commit" value="compost" data-disable-with="compost" style="background: url('/images/buttons/compost-button.png') no-repeat center center; width: 60px; height: 60px; margin: 0px 20px; border: none; color: transparent; border-radius: 5px">


  <% end %>

</div>

<% if false %>
<img src="/images/buttons/trash-button.png" class="answer-button" alt="trash">
<%= submit_tag value='trash' %>
<img src="/images/buttons/recycle-button.png" class="answer-button" alt="recycling">
<%= submit_tag value='recycling' %>
<img src="/images/buttons/compost-button.png" class="answer-button" alt="compost">
<%= submit_tag value='compost' %>
<% end %>

app/views/hoods/index.erb
<div class="hoods-box">

  <div style="float: left"">

    <h2>Green Up Leaderboard:</h2>
      <% ranked = @hoods.sort_by { |hood| hood.hood_score }.reverse %>
      <ol style="font-size: 16pt">
        <% ranked.each do |hood| %>
          <% if hood == ranked.first %>
            <li class="hood-list" style="font-weight: bold"><%= link_to hood.name, hood %> - <%= hood.hood_score %></li>
          <% else %>
            <li class="hood-list"><%= link_to hood.name, hood %> - <%= hood.hood_score %></li>
          <% end %>
        <% end %>
      </ol>
    </div>
      <div>
        <img src="/seattle-hoods-map.jpg" alt="map of the hoods" class="map-image">
      </div>
</div>

app/views/hoods/resources.html.erb
<div class="container list-box">
<h2 style="padding-left: 20px">Resources:</h2>
<br>
  <ul>
    <li><a class="resource" href="http://www.seattle.gov/utilities/services/where-does-it-go" target="_blank" rel="noopener noreferrer">Seattle.gov - Where Does It Go?</a></li>
    <li><a class="resource" href="https://www.recycleguide.org/seattle-wa-recycles/" target="_blank" rel="noopener noreferrer">Recycle Guide - Seattle Recycles Too</a></li>
    <li><a class="resource" href="https://www.kingcounty.gov/~/media/depts/dnrp/solid-waste/garbage-recycling/documents/recycling-yardwaste-food-garbage-guide.ashx?la=en" target="_blank" rel="noopener noreferrer">King County Garbage/Recycling Guide</a></li>
    <li><a class="resource" href="https://www.seattletimes.com/seattle-news/what-do-i-do-with-a-guide-to-trash-sorting-in-seattle/" target="_blank" rel="noopener noreferrer">Seattle Times - What Do I Do With . . ?</a></li>
    <li><a class="resource"  href="http://www.myyp.com/guide/Seattle,WA/Recycling-Guide" target="_blank" rel="noopener noreferrer">Valley Yellow Pages Recycling Guide</a></li>
  </ul>

</div>

app/views/hoods/show.erb
<div class="container show" align="center">
  <span class="fas fa-users" style="font-size: 70px; padding-top: 20px; color: #009444"></span>
  <h2><%= @hood.name %></h2>

  <%= form_tag '/hoods', method: :get do %>
    <div class='button'> <%= submit_tag 'Back' %> </div>
  <% end %>

  <h3> Total Points: <%= @hood.hood_score %> </h3>

  <% if @hood == Hood.all.max_by(&:hood_score) %>
    <h4>Congrats <%= @hood.name.split.last %>, you're in first place!</h4>

  <% else %>
    <% @hoods = Hood.all.sort_by(&:hood_score).reverse %>
    <% (1..@hoods.count-1).to_a.each do |place| %>

      <% if @hoods[place] == @hood %>
        <h4> <%= (place + 1).ordinalize %> Place Overall</h4>
        <h4> Only <%= (@hoods[place-1].hood_score+10) - @hood.hood_score %> points to beat the <%= @hoods[place-1].name %>!</h4>
      <% end %>
    <% end %>

  <% end %>

  <h3> Team Neighborhoods: </h3>

    <% @hood.sub_hoods.each do |sub_hood| %>
      <p><%= sub_hood.name %> </p>
    <% end %>

  <h3> Team Members: </h3>

    <% @users.each do |user| %>
      <% if user.hood_id == @hood.id %>
      <p><%= link_to user.name, user %></p>
      <% end %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <link rel="icon" href="/favicon.ico">
    <!-- <link rel="stylesheet" href="/stylesheets/users.scss"> -->
    <link href="https://fonts.googleapis.com/css?family=PT+Sans" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <title>Green Up! Seattle</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navigation' %>
    <main>
      <%= yield %>
    </main>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_footer.erb
<footer class="footer">
  <div class="container">
    <span class="text-muted">
    
    </span>
  </div>
</footer>

app/views/shared/_navigation.html.erb
<% if logged_in %>
  <% @user = User.find(session[:user_id]) %>
<% end %>

<nav class="navbar navbar-default" role="navigation">
  <div class="container-nav">
    <div class="navbar-header">
      <a class="navbar-brand" href="/"><img src="/green_up_logo.svg" alt="Green Up Seattle Logo"></a>
      <div class="navbar-links">
        <a class="navbar-text" href="/hoods">Hoods</a>
        <a class="navbar-text" href="/games">Play Game</a>
        <a class="navbar-text" href="/resources">Resources</a>
        <% if logged_in %>
        <a class="navbar-text" href="/logout">Logout</a>
        <a class="navbar-text" href="/users/<%= @user.id %>"><i class="fas fa-user-circle"></i> &nbsp;<%= @user.username %></a>
        <% else %>
        <a class="navbar-text" href='/'>Log In</a>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/users/index.html.erb
<!-- <h1>GreenUp! Seattle</h1> -->
<% if logged_in %>
  <h3 class="message"><%=flash[:message]%></h3>
  <br>
<% end %>

<div class="container intro">
  <p><span style="font-size: 1.6em; color: #009444">Green Up Seattle</span> is dedicated to helping reduce the misplaced waste problem in the city of Seattle. Create an account and you can help your neighborhood earn green points.</p>
  <p><i class="fas fa-check" style="color: #009444"></i> Earn points by playing Bin It to Win It, a waste sorting game, to improve your knowledge of proper waste disposal.</p>
  <p><i class="fas fa-check" style="color: #009444"></i> The neighborhood with the most points at the end of each month will get 20% off their recycling bill for the month!</p>
  <p><i class="fas fa-check" style="color: #009444"></i> Want to brush up on your skills before playing? Visit our resources page for waste guidelines and more useful information.</p>
</div>
<br>
<% if logged_in %>
<center><a href='/games' class="btn btn-success">PLAY GAME</a></center>
<% end %>
<br>
<% if !logged_in %>
<div class="log-in-box">
  <h4>Log in:</h4>
  <br>
  <%= form_tag('/', method: :post) do %>
    <%= label_tag "User name: " %>
    <%= text_field_tag :username %>
    <br><br>
    <%= label_tag "Password: " %>
    <%= password_field_tag :password %>
    <br>
    <div class="error"><%= flash[:message] %></div>
    <br>
    <button type="submit" class="btn btn-primary" submit_tag="Login">Log In</button>
  <% end %>
<br>
<p>New? <%= link_to "Create an account", new_user_path %></p>
</div>

<% end %>

app/views/users/new.html.erb
<% if logged_in %>
  <h3 class="message">Edit your account</h3>
<% else %>
  <h3 class="message">Create an account</h3>
<% end %>
<br>
<div class="create-box"> <!-- start of box -->

<style>

#right {
  text-align: right
}
</style>

  <div style="float: left">
  <% @w = 28 %>
  <%= form_for @user do |f| %>
      <%= f.label :name %><br>
      <%= f.text_field :name, size: @w %>
      <br><br>
      <%= f.label :username %><br>
      <%= f.text_field :username, size: @w %>
      <br><br>
      <%= f.label :password %><br>
      <%= f.password_field :password, size: @w %>
      <br><br>
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation, size: @w %>
      <br><br>
      <%= f.label :hood_id %> <br>
      <%= f.collection_select(:hood_id, Hood.all.sort_by(&:id), :id, :name_with_id, include_blank: 'Select your \'hood') %>
      <br><br>
    <% if logged_in %>
      <%= f.submit name="Update" %>
    <% else %>
      <%= f.submit name="Create"%>
    <% end %>
  <% end %>
<br>
  <% if @errors %>
    <ul>
      <% @errors.each do |error| %>
      <li class="error"><%= error %></li>
      <% end %>
    </ul>
  <% end %>
  </div>
  <div>
    <img src="/seattle-hoods-map.jpg" alt="map of the hoods" class="map-image">
  </div>

</div> <!-- end of box -->

app/views/users/show.html.erb
<div class="container profile">
  <span class="fas fa-user-circle" style="font-size: 30pt"></span>
  <h3><%= @user.username %></h3>
  <hr>
  <span class="underline">Name:</span>
  <h4><%= @user.name %></h4>
  <span class="underline">Neighborhood:</span>
  <h4><%= @user.hood.name %></h4>
  <span class="underline">Level:</span>
  <h4><%= @user.level %></h4>
  <span class="underline">Total Points:</span>
  <h4><%= @user.points / 2 %></h4>
  <br>
  <% if @user.id == session[:user_id] %>
    <p><%= link_to 'Edit Profile', {action: "edit", method: :get, id: @user.id}, {class: "btn btn-primary"} %></p>

    <p><%= button_to "Delete Profile", user_path(@user), method: :delete, class: "btn btn-danger", data: {confirm: "Are you sure?"} %></p>
  <% end %>
</div>